using System;
using Microsoft.EntityFrameworkCore;

namespace DigitalHealthCheckEF
{

    [Keyless]
    public class AnonymisedPatient
    {
        public Guid Id {get;set;}
        public string PredictedCVDRisk {get;set;}
        public string PredictedDiabetesRisk {get;set;}
        public string InviteDate {get;set;}
        public string NHSHCTextLink {get;set;}
        public string NHSHCQRCode {get;set;}
        public bool ArrivedAtLandingPage {get;set;}
        public bool? StartedNHSHealthCheck {get;set;}
        public bool? HeightAndWeightKnown {get;set;}
        public bool? HeightAndWeightNotKnown {get;set;}
        public float? Height {get;set;}
        public float? Weight {get;set;}
        public double? BMI {get;set;}
        public string SexAssignedAtBirth {get;set;}
        public string PreferredSexForFirstViewOfResults {get;set;}
        public string Ethnicity {get;set;}
        public string SmokingStatus {get;set;}
        public string SmokingBehaviour {get;set;}
        public bool? DrinksAlcohol {get;set;}
        public string DrinkingFrequency {get;set;}
        public string DrinkingUnits {get;set;}
        public string MSASQ {get;set;}
        public string UnableToStop {get;set;}
        public string FailedResponsibilityDueToAlcohol {get;set;}
        public string NeededToDrinkAlcoholMorningAfter {get;set;}
        public string GuiltAfterDrinking {get;set;}
        public string MemoryLossAfterDrinking {get;set;}
        public string InjuryCausedByDrinking {get;set;}
        public string ContactsConcernedByDrinking {get;set;}
        public string WorkActivity {get;set;}
        public string PhysicalActivity {get;set;}
        public string Cycling {get;set;}
        public string Housework {get;set;}
        public string Gardening {get;set;}
        public string Walking {get;set;}
        public string WalkingPace {get;set;}
        public string KnowYourHbA1c {get;set;}
        public string HbA1cMeasure {get;set;}
        public bool? HbA1cMeasureFound {get;set;}
        public string KnowYourBloodPressure {get;set;}
        public string BloodPressureMeasureSys {get;set;}
        public string BloodPressureMeasureDias {get;set;}
        public bool? BloodPressureMeasureFound {get;set;}
        public string KnowYourCholesterol {get;set;}
        public string CholesterolMeasureTotal {get;set;}
        public string CholesterolMeasureHDL {get;set;}
        public bool? CholesterolMeasureFound {get;set;}
        public bool? FeelingDown {get;set;}
        public bool? Disinterested {get;set;}
        public string Anxious {get;set;}
        public string Worrying {get;set;}
        public bool? SkipMentalHealthQuestions {get;set;}
        public bool? EmailProvided {get;set;}
        public bool? PhoneNumberProvided {get;set;}
        public bool? SmsNumberProvided {get;set;}
        public int? IMDQuintile {get;set;}
        public string Lsoa {get;set;}
        public int? Age {get;set;}
        public bool? ValidationConfirmed {get;set;}
        public bool? ValidationCompleted {get;set;}
        public string GPSurgery {get;set;}
        public bool? SubmittedCheckYourAnswers {get;set;}
        public bool? HeightAndWeightFollowUp {get;set;}
        public bool? ReceivedHealthCheckIncompleteEmail {get;set;}
        public string HeightAndWeightImportance {get;set;}
        public string HeightAndWeightConfidence {get;set;}
        public string HeightAndWeightMethodOfMeasurement {get;set;}
        public bool? HeightAndWeightIntentions {get;set;}
        public bool? HeightAndWeightSetADate {get;set;}
        public bool? HeightAndWeightReminderRequest {get;set;}
        public bool? ViewsResults {get;set;}
        public string CVDRiskCategory {get;set;}
        public string CVDBehaviours {get;set;}
        public double? CVDRiskScore {get;set;}
        public int? HeartAge {get;set;}
        public string HeartAgeRiskCategory {get;set;}
        public string QDiabetesScoreCategory {get;set;}
        public double? QDiabetes {get;set;}
        public string Alcohol {get;set;}
        public string PhysicalActivityLevel {get;set;}
        public string BMICategory {get;set;}
        public string BloodPressureCategory {get;set;}
        public string HbA1cCategory {get;set;}
        public string CholesterolCategory {get;set;}
        public int? ModifiableFactorsCount {get;set;}
        public bool? NonUrgentGPFollowUp {get;set;}
        public bool? UrgentGPFollowUp {get;set;}
        public string FirstHealthPriorityAfterResults {get;set;}
        public string SecondHealthPriorityAfterResults {get;set;}
        public string FirstFollowUpOptionSelected {get;set;}
        public bool? BookGPFollowUpPageCompleted {get;set;}
        public string GPFollowUpImportance {get;set;}
        public string GPFollowUpConfidence {get;set;}
        public bool? GPFollowUpIntentions {get;set;}
        public bool? GPFollowUpSetADate {get;set;}
        public bool? GPFollowUpReminderRequest {get;set;}
        public int? GPFollowUpNumberOfBarriers {get;set;}
        public int? GPFollowUpNumberOfActions {get;set;}
        public bool? MeasureBloodPressureFollowUpPageCompleted {get;set;}
        public string MeasureBloodPressureFollowUpImportance {get;set;}
        public string MeasureBloodPressureFollowUpConfidence {get;set;}
        public string MeasureBloodPressureFollowUpMethodOfMeasurement {get;set;}
        public bool? MeasureBloodPressureFollowUpIntentions {get;set;}
        public bool? MeasureBloodPressureFollowUpSetADate {get;set;}
        public bool? MeasureBloodPressureFollowUpReminderRequest {get;set;}
        public int? MeasureBloodPressureFollowUpNumberOfBarriers {get;set;}
        public int? MeasureBloodPressureFollowUpNumberOfActions {get;set;}
        public bool? ImproveBloodPressureFollowUpPageCompleted {get;set;}
        public string ImproveBloodPressureFollowUpImportance {get;set;}
        public string ImproveBloodPressureFollowUpConfidence {get;set;}
        public bool? ImproveBloodPressureFollowUpIntentions {get;set;}
        public bool? ImproveBloodPressureFollowUpSetADate {get;set;}
        public bool? ImproveBloodPressureFollowUpReminderRequest {get;set;}
        public int? ImproveBloodPressureFollowUpNumberOfBarriers {get;set;}
        public int? ImproveBloodPressureFollowUpNumberOfActions {get;set;}
        public bool? MeasureBloodSugarFollowUpPageCompleted {get;set;}
        public string MeasureBloodSugarFollowUpImportance {get;set;}
        public string MeasureBloodSugarFollowUpConfidence {get;set;}
        public string  MeasureBloodSugarFollowUpMethodOfMeasurement {get;set;}
        public bool? MeasureBloodSugarFollowUpIntentions {get;set;}
        public bool? MeasureBloodSugarFollowUpSetADate {get;set;}
        public bool? MeasureBloodSugarFollowUpReminderRequest {get;set;}
        public int? MeasureBloodSugarFollowUpNumberOfBarriers {get;set;}
        public int? MeasureBloodSugarFollowUpNumberOfActions {get;set;}
        public bool? ImproveBloodSugarFollowUpPageCompleted {get;set;}
        public string ImproveBloodSugarFollowUpImportance {get;set;}
        public string ImproveBloodSugarFollowUpConfidence {get;set;}
        public bool? ImproveBloodSugarFollowUpIntentions {get;set;}
        public bool? ImproveBloodSugarFollowUpSetADate {get;set;}
        public bool? ImproveBloodSugarFollowUpReminderRequest {get;set;}
        public int? ImproveBloodSugarFollowUpNumberOfBarriers {get;set;}
        public int? ImproveBloodSugarFollowUpNumberOfActions {get;set;}
        public bool? MeasureCholesterolFollowUpPageCompleted {get;set;}
        public string MeasureCholesterolFollowUpImportance {get;set;}
        public string MeasureCholesterolFollowUpConfidence {get;set;}
        public string  MeasureCholesterolFollowUpMethodOfMeasurement {get;set;}
        public bool? MeasureCholesterolFollowUpIntentions {get;set;}
        public bool? MeasureCholesterolFollowUpSetADate {get;set;}
        public bool? MeasureCholesterolFollowUpReminderRequest {get;set;}
        public int? MeasureCholesterolFollowUpNumberOfBarriers {get;set;}
        public int? MeasureCholesterolFollowUpNumberOfActions {get;set;}
        public bool? ImproveCholesterolFollowUpPageCompleted {get;set;}
        public string ImproveCholesterolFollowUpImportance {get;set;}
        public string ImproveCholesterolFollowUpConfidence {get;set;}
        public bool? ImproveCholesterolFollowUpIntentions {get;set;}
        public bool? ImproveCholesterolFollowUpSetADate {get;set;}
        public bool? ImproveCholesterolFollowUpReminderRequest {get;set;}
        public int? ImproveCholesterolFollowUpNumberOfBarriers {get;set;}
        public int? ImproveCholesterolFollowUpNumberOfActions {get;set;}
        public bool? StopSmokingFollowUpPageCompleted {get;set;}
        public string StopSmokingFollowUpImportance {get;set;}
        public string StopSmokingFollowUpConfidence {get;set;}
        public bool? StopSmokingFollowUpIntentions {get;set;}
        public bool? StopSmokingFollowUpSetADate {get;set;}
        public bool? StopSmokingFollowUpReminderRequest {get;set;}
        public int? StopSmokingFollowUpNumberOfBarriers {get;set;}
        public int? StopSmokingFollowUpNumberOfActions {get;set;}
        public bool? QuitDrinkingFollowUpPageCompleted {get;set;}
        public string QuitDrinkingFollowUpImportance {get;set;}
        public string QuitDrinkingFollowUpConfidence {get;set;}
        public bool? QuitDrinkingFollowUpIntentions {get;set;}
        public bool? QuitDrinkingFollowUpSetADate {get;set;}
        public bool? QuitDrinkingFollowUpReminderRequest {get;set;}
        public int? QuitDrinkingFollowUpNumberOfBarriers {get;set;}
        public int? QuitDrinkingFollowUpNumberOfActions {get;set;}
        public bool? HealthyWeightFollowUpPageCompleted {get;set;}
        public string HealthyWeightFollowUpImportance {get;set;}
        public string HealthyWeightFollowUpConfidence {get;set;}
        public bool? HealthyWeightFollowUpIntentions {get;set;}
        public bool? HealthyWeightFollowUpSetADate {get;set;}
        public bool? HealthyWeightFollowUpReminderRequest {get;set;}
        public int? HealthyWeightFollowUpNumberOfBarriers {get;set;}
        public int? HealthyWeightFollowUpNumberOfActions {get;set;}
        public bool? MoveMoreFollowUpPageCompleted {get;set;}
        public string MoveMoreFollowUpImportance {get;set;}
        public string MoveMoreFollowUpConfidence {get;set;}
        public bool? MoveMoreFollowUpIntentions {get;set;}
        public bool? MoveMoreFollowUpSetADate {get;set;}
        public bool? MoveMoreFollowUpReminderRequest {get;set;}
        public int? MoveMoreFollowUpNumberOfBarriers {get;set;}
        public int? MoveMoreFollowUpNumberOfActions {get;set;}
        public bool? MentalHealthFollowUpPageCompleted {get;set;}
        public string MentalHealthFollowUpImportance {get;set;}
        public string MentalHealthFollowUpConfidence {get;set;}
        public bool? MentalHealthFollowUpIntentions {get;set;}
        public bool? MentalHealthFollowUpSetADate {get;set;}
        public bool? MentalHealthFollowUpReminderRequest {get;set;}
        public int? MentalHealthFollowUpNumberOfBarriers {get;set;}
        public int? MentalHealthFollowUpNumberOfActions {get;set;}
        public bool? PatientEligibleForEveryoneHealthReferral {get;set;}
        public string MethodOfContactForEveryoneHealth {get;set;}
        public bool? RecommendedBiometricAssessments {get;set;}
        public bool? HealthCheckCompleted {get;set;}
        public bool? ContactInformationUpdatedOnComplete {get;set;}
        public bool? HeightAndWeightUpdated {get;set;}
        public bool? BloodSugarUpdated {get;set;}
        public bool? BloodPressureUpdated {get;set;}
        public bool? CholesterolUpdated {get;set;}
        public bool? FamilyHistoryDiabetes {get;set;}
        public bool? FamilyHistoryCVD {get;set;}
        public bool? ChronicKidneyDisease {get;set;}
        public bool? AtrialFibrillation {get;set;}
        public bool? BloodPressureTreatment {get;set;}
    }
}