using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace DigitalHealthCheckEF
{
    public class Database : DbContext
    {
        //We can hard-code these ids because they are set programatically in our migrations.
        //If this changes, we'll need to use a different identifier.
        public const int AuditOver8BarrierId = 46; //I can't stop drinking even if I want to 
        public const int NeedMentalHealthReferralBarrierId = 47; //I need to speak with someone to help improve my mental wellbeing

        public const int BmiOver30InterventionId = 24; //Send me a link to holistic healthy weight services for BMI 30+
        public const int BmiOver40InterventionId = 25; //Send me a link to holistic healthy weight services for BMI 40+
        public const int NationalDiabetesPreventionProgramInterventionId = 125; //Direct me to the NHS Diabetes Prevention Programme self-referral registration page

        public const int EveryoneHealthSmokingReferral = 11;
        public const int EveryoneHealthWeightReferral = 28;
        public const int EveryoneHealthMoveReferral = 45;
        public const int EveryoneHealthAlcoholReferral = 56;
        public const int EveryoneHealthMentalReferral = 60;
        public const int EveryoneHealthCholesterolReferral = 112;
        public const int EveryoneHealthBloodSugarReferral = 124;
        public const int EveryoneHealthBloodPressureReferral = 136;

        public virtual DbSet<Barrier> Barriers { get; set; }

        public virtual DbSet<CustomBarrier> CustomBarriers { get; set; }

        public virtual DbSet<HealthCheck> HealthChecks { get; set; }

        public virtual DbSet<Intervention> Interventions { get; set; }

        public virtual DbSet<ValidationError> ValidationErrors { get; set; }

        public virtual DbSet<IdentityVariant> IdentityVariants { get; set; }

        public virtual DbSet<Townsend> Townsend { get; set; }

        public virtual DbSet<Setting> Settings { get; set; }

        public virtual DbSet<BloodKitRequest> BloodKitRequests { get; set; }

        public IQueryable<UptakeRateReport> UptakeRateReport(DateTime? start = null, DateTime? end = null) =>
            FromExpression(() => UptakeRateReport(start, end));

        public IQueryable<DetailedUptakeReport> DetailedUptakeReport(DateTime? start = null, DateTime? end = null) =>
            FromExpression(() => DetailedUptakeReport(start, end));

        public IQueryable<InterventionEligibilityReport> InterventionEligibilityReport(DateTime? start = null, DateTime? end = null) =>
            FromExpression(() => InterventionEligibilityReport(start, end));

        public IQueryable<BiometricAssessmentSuccessReport> BiometricAssessmentSuccessReport(DateTime? start = null, DateTime? end = null) =>
            FromExpression(() => BiometricAssessmentSuccessReport(start, end));

        public IQueryable<AnonymisedPatient> AnonymisedDataSet(DateTime? start = null, DateTime? end = null) =>
            FromExpression(() => AnonymisedDataSet(start, end));

        public IQueryable<AnonymisedBarrier> AnonymisedBarriers(DateTime? start = null, DateTime? end = null) =>
            FromExpression(() => AnonymisedBarriers(start, end));

        public IQueryable<AnonymisedIntervention> AnonymisedInterventions(DateTime? start = null, DateTime? end = null) =>
            FromExpression(() => AnonymisedInterventions(start, end));

        public Database(DbContextOptions<Database> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasDbFunction(typeof(Database).GetMethod(nameof(AnonymisedDataSet), new[] { typeof(DateTime?), typeof(DateTime?) }));

            modelBuilder.HasDbFunction(typeof(Database).GetMethod(nameof(AnonymisedBarriers), new[] { typeof(DateTime?), typeof(DateTime?) }));

            modelBuilder.HasDbFunction(typeof(Database).GetMethod(nameof(AnonymisedInterventions), new[] { typeof(DateTime?), typeof(DateTime?) }));

            modelBuilder.HasDbFunction(typeof(Database).GetMethod(nameof(UptakeRateReport), new[] { typeof(DateTime?), typeof(DateTime?) }));

            modelBuilder.HasDbFunction(typeof(Database).GetMethod(nameof(DetailedUptakeReport), new[] { typeof(DateTime?), typeof(DateTime?) }));

            modelBuilder.HasDbFunction(typeof(Database).GetMethod(nameof(InterventionEligibilityReport), new[] { typeof(DateTime?), typeof(DateTime?) }));

            modelBuilder.HasDbFunction(typeof(Database).GetMethod(nameof(BiometricAssessmentSuccessReport), new[] { typeof(DateTime?), typeof(DateTime?) }));

            modelBuilder.Entity<Intervention>()
                .HasOne<Barrier>(e => e.Barrier)
                .WithMany(b => b.Interventions)
                .IsRequired(false)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<Barrier>().HasData
            (
                new Barrier { Id = 1, Category = "smoking", Order = 1, Text = "All of my friends smoke" },
                new Barrier { Id = 2, Category = "smoking", Order = 2, Text = "I do not have access to smoking cessation aids (e.g. nicotine patches, vaping)" },
                new Barrier { Id = 3, Category = "smoking", Order = 3, Text = "I do not know how to quit" },
                new Barrier { Id = 6, Category = "smoking", Order = 4, Text = "I enjoy smoking/I use smoking to manage stress" },
                new Barrier { Id = 7, Category = "smoking", Order = 5, Text = "I have tried to quit smoking before and failed" },
                new Barrier { Id = 8, Category = "smoking", Order = 6, Text = "I do not have the will power/motivation to quit smoking" },
                new Barrier { Id = 9, Category = "smoking", Order = 7, Text = "I do not see the benefit of cutting down or quitting smoking" },
                new Barrier { Id = 10, Category = "smoking", Order = 8, Text = "I have strong nicotine cravings" },
                new Barrier { Id = 11, Category = "weight", Order = 1, Text = "I do not know what a healthy diet involves" },
                new Barrier { Id = 12, Category = "weight", Order = 2, Text = "I do not know how to lose weight" },
                new Barrier { Id = 13, Category = "weight", Order = 3, Text = "I do not have anyone to become more healthy with" },
                new Barrier { Id = 14, Category = "weight", Order = 4, Text = "I cannot afford to eat well" },
                new Barrier { Id = 15, Category = "weight", Order = 5, Text = "I do not have access to healthy food" },
                new Barrier { Id = 16, Category = "weight", Order = 6, Text = "I feel stressed which impacts my unhealthy eating habits " },
                new Barrier { Id = 17, Category = "weight", Order = 7, Text = "I do not have access to a gym or swimming facilities to help me move more" },
                new Barrier { Id = 18, Category = "weight", Order = 8, Text = "I do not see how moving more can help me to be healthier" },
                new Barrier { Id = 19, Category = "weight", Order = 9, Text = "I am worried people at what people might think of me if I try to become more active or attempt to eat more healthily" },
                new Barrier { Id = 20, Category = "weight", Order = 10, Text = "I do not know how to get started on moving more" },
                new Barrier { Id = 21, Category = "weight", Order = 11, Text = "I do not know how to track what I am eating" },
                new Barrier { Id = 22, Category = "weight", Order = 12, Text = "I do not know how to track and build up my activity levels  " },
                new Barrier { Id = 23, Category = "weight", Order = 13, Text = "I do not believe that I am good at sport" },
                new Barrier { Id = 24, Category = "move", Order = 1, Text = "I do not have the motivation or will power to move more" },
                new Barrier { Id = 25, Category = "move", Order = 2, Text = "I have no one to exercise with" },
                new Barrier { Id = 26, Category = "move", Order = 3, Text = "I have a health condition which makes it difficult to build physical activity into my life" },
                new Barrier { Id = 27, Category = "move", Order = 4, Text = "I can't afford to pay for exercise activities " },
                new Barrier { Id = 28, Category = "move", Order = 5, Text = "I do not know what healthy levels of exercise are" },
                new Barrier { Id = 29, Category = "move", Order = 6, Text = "I do not know how to run" },
                new Barrier { Id = 30, Category = "move", Order = 7, Text = "I do not know what support programmes are available to suit my level of activity" },
                new Barrier { Id = 32, Category = "move", Order = 9, Text = "I do not know how to get started in moving more" },
                new Barrier { Id = 33, Category = "move", Order = 10, Text = "I am worried people will laugh at me if I try to become more active" },
                new Barrier { Id = 34, Category = "move", Order = 11, Text = "I do not see how moving more can help me to be healthier" },
                new Barrier { Id = 35, Category = "move", Order = 12, Text = "I do not have access to a gym or swimming facilities to help me move more" },
                new Barrier { Id = 36, Category = "move", Order = 13, Text = "I do not believe that I am good at sport" },
                new Barrier { Id = 37, Category = "move", Order = 14, Text = "I do not have time to be physically active" },
                new Barrier { Id = 38, Category = "alcohol", Order = 1, Text = "I do not think the amount I am drinking is bad for my health" },
                new Barrier { Id = 39, Category = "alcohol", Order = 2, Text = "I am not sure of the health impact of excessive drinking" },
                new Barrier { Id = 40, Category = "alcohol", Order = 3, Text = "I do not know how to cut down my alcohol intake" },
                new Barrier { Id = 41, Category = "alcohol", Order = 4, Text = "I do not know how to meet more people and socialise in a way that doesn't involve alcohol" },
                new Barrier { Id = 42, Category = "alcohol", Order = 5, Text = "I do not have friends or family that I can talk to that understand my drinking difficulties" },
                new Barrier { Id = 43, Category = "alcohol", Order = 6, Text = "I use drinking to manage stress" },
                new Barrier { Id = 44, Category = "alcohol", Order = 7, Text = "There is often alcohol in my home" },
                new Barrier { Id = 45, Category = "alcohol", Order = 8, Text = "My mental wellbeing impacts my drinking habits" },
                new Barrier { Id = 46, Category = "alcohol", Order = 9, Text = "I cannot stop drinking even if I want to " },
                new Barrier { Id = 47, Category = "mental", Order = 1, Text = "I need to speak with someone to help improve my mental wellbeing" },
                new Barrier { Id = 48, Category = "mental", Order = 2, Text = "I do not know where to access information and support on mental wellbeing services in Southwark" },
                new Barrier { Id = 49, Category = "mental", Order = 3, Text = "I do not believe that physical exercise can improve my mental wellbeing" },
                new Barrier { Id = 50, Category = "mental", Order = 4, Text = "I need support that fits around my needs and busy lifestyle" },
                new Barrier { Id = 53, Category = "mental", Order = 5, Text = "I do not know what physical activities I can do to help improve my mood" },
                new Barrier { Id = 55, Category = "mental", Order = 6, Text = "I have difficulty sleeping which affects my mental wellbeing" },
                new Barrier { Id = 57, Category = "mental", Order = 7, Text = "I do not have any tools to help me relax" },
                new Barrier { Id = 59, Category = "mental", Order = 8, Text = "I do not have anyone to connect with that can relate to my unique experiences" },
                new Barrier { Id = 62, Category = "mental", Order = 9, Text = "I feel lonely and socially isolated" },
                new Barrier { Id = 65, Category = "mental", Order = 10, Text = "I cannot find ways to express myself creatively" },
                new Barrier { Id = 67, Category = "mental", Order = 11, Text = "I do not have the skills to alter my ways of negative thinking" },
                new Barrier { Id = 68, Category = "mental", Order = 12, Text = "I am struggling with my gender identity or sexual orientation, including discrimination" },
                new Barrier { Id = 70, Category = "mental", Order = 13, Text = "I do not know where to access mental health support services that can help me to manage my anxiety and depression and which address topics such as discrimination, bereavement and coping during the pandemic" },
                new Barrier { Id = 71, Category = "mental", Order = 14, Text = "I am struggling with housing issues" },
                new Barrier { Id = 73, Category = "mental", Order = 15, Text = "I am struggling with employment problems" },
                new Barrier { Id = 74, Category = "mental", Order = 16, Text = "I am struggling with childcare problems" },
                new Barrier { Id = 76, Category = "mental", Order = 17, Text = "As a carer who looks after the needs of someone else, I am struggling to look after my own wellbeing" },
                new Barrier { Id = 77, Category = "mental", Order = 18, Text = "I am struggling with my bills" },
                new Barrier { Id = 78, Category = "mental", Order = 19, Text = "I am struggling to afford food" },
                new Barrier { Id = 79, Category = "mental", Order = 20, Text = "I am struggling with money issues" },
                new Barrier { Id = 81, Category = "mental", Order = 21, Text = "I need help coping with bereavement" },
                new Barrier { Id = 83, Category = "gp", Order = 1, Text = "I do not see the point" },
                new Barrier { Id = 84, Category = "gp", Order = 2, Text = "I do not think it will do me any good" },
                new Barrier { Id = 85, Category = "gp", Order = 3, Text = "I do not have time" },
                new Barrier { Id = 86, Category = "gp", Order = 4, Text = "It is hard to get an appointment" },
                new Barrier { Id = 87, Category = "gp", Order = 5, Text = "I have mobility limitations" },
                new Barrier { Id = 88, Category = "gp", Order = 6, Text = "I do not like doctors" },
                new Barrier { Id = 89, Category = "gp", Order = 7, Text = "I am afraid (of the results)" },
                new Barrier { Id = 90, Category = "gp", Order = 8, Text = "I do not want to overstretch the NHS" },
                new Barrier { Id = 91, Category = "improvecholesterol", Order = 1, Text = "I do not know what foods I should eat or avoid that will help lower my cholesterol" },
                new Barrier { Id = 92, Category = "improvecholesterol", Order = 2, Text = "I do not have time to be physically active" },
                new Barrier { Id = 93, Category = "improvecholesterol", Order = 3, Text = "I do not know how to get started to moving more" },
                new Barrier { Id = 94, Category = "improvecholesterol", Order = 4, Text = "I feel stressed which impacts my unhealthy lifestyle habits" },
                new Barrier { Id = 95, Category = "improvecholesterol", Order = 5, Text = "I do not believe that my cholesterol levels are bad for my health " },
                new Barrier { Id = 96, Category = "improvecholesterol", Order = 6, Text = "I do not know what lifestyle changes I can make to lower my cholesterol " },
                new Barrier { Id = 97, Category = "improvecholesterol", Order = 7, Text = "I know that drinking less alcohol can help lower my cholesterol, but I do not have opportunities to socialise that do not include alcohol" },
                new Barrier { Id = 99, Category = "improvecholesterol", Order = 8, Text = "I know that I should cut down on smoking to help lower my cholesterol, but I do not have the will power or motivation to quit" },
                new Barrier { Id = 100, Category = "improvebloodpressure", Order = 1, Text = "I do not know what lifestyle changes I can make to lower my blood pressure" },
                new Barrier { Id = 101, Category = "improvebloodpressure", Order = 2, Text = "I do not see how moving more can help me to be healthier" },
                new Barrier { Id = 102, Category = "improvebloodpressure", Order = 3, Text = "I do not have the will power to make healthy lifestyle changes that will help lower my blood pressure" },
                new Barrier { Id = 103, Category = "improvebloodpressure", Order = 4, Text = "I know that I should cut down on smoking to help lower my blood pressure, but I do not have the will power or motivation to quit" },
                new Barrier { Id = 104, Category = "improvebloodpressure", Order = 5, Text = "I know that a lack of sleep can impact blood pressure but I have difficulty sleeping" },
                new Barrier { Id = 105, Category = "improvebloodpressure", Order = 6, Text = "I do not know how to cut down my salt intake" },
                new Barrier { Id = 106, Category = "improvebloodpressure", Order = 7, Text = "I do not have time to be physically active" },
                new Barrier { Id = 107, Category = "improvebloodpressure", Order = 8, Text = "I do not know how to track what I am eating" },
                new Barrier { Id = 108, Category = "improvebloodpressure", Order = 9, Text = "I need to lose weight to help lower my blood pressure, but I do not know how to" },
                new Barrier { Id = 109, Category = "improvebloodpressure", Order = 10, Text = "I do not have anyone to eat more healthily and become more active with" },
                new Barrier { Id = 110, Category = "improvebloodsugar", Order = 1, Text = "I do not think that I can eat healthily" },
                new Barrier { Id = 111, Category = "improvebloodsugar", Order = 2, Text = "I do not see why I should be concerned about my blood sugar levels" },
                new Barrier { Id = 112, Category = "improvebloodsugar", Order = 3, Text = "I comfort eat when I am feeling low, anxious or stressed" },
                new Barrier { Id = 113, Category = "improvebloodsugar", Order = 4, Text = "I do not know how to track what I am eating" },
                new Barrier { Id = 114, Category = "improvebloodsugar", Order = 5, Text = "I do not believe that I am capable of moving more" },
                new Barrier { Id = 115, Category = "improvebloodsugar", Order = 6, Text = "I do not know how to move more" },
                new Barrier { Id = 116, Category = "improvebloodsugar", Order = 7, Text = "I do not have access to a gym or swimming facilities to help me move more" },
                new Barrier { Id = 117, Category = "improvebloodsugar", Order = 8, Text = "I cannot tell how much sugar is in the foods that I buy" },
                new Barrier { Id = 118, Category = "improvebloodsugar", Order = 9, Text = "I do not have anyone to eat more healthily and become more active with" },
                new Barrier { Id = 119, Category = "cholesterol", Order = 1, Text = "I do not see the point" },
                new Barrier { Id = 120, Category = "cholesterol", Order = 2, Text = "I do not have time" },
                new Barrier { Id = 121, Category = "cholesterol", Order = 3, Text = "It is hard to get an appointment at the GP clinic to get my cholesterol measured" },
                new Barrier { Id = 122, Category = "cholesterol", Order = 4, Text = "I have mobility limitations" },
                new Barrier { Id = 124, Category = "cholesterol", Order = 5, Text = "I am afraid of the results from my blood test" },
                new Barrier { Id = 125, Category = "cholesterol", Order = 6, Text = "I am afraid of needles" },
                new Barrier { Id = 126, Category = "bloodsugar", Order = 1, Text = "I do not see the point" },
                new Barrier { Id = 127, Category = "bloodsugar", Order = 2, Text = "I do not have time" },
                new Barrier { Id = 128, Category = "bloodsugar", Order = 3, Text = "It is hard to get an appointment at the GP clinic to get my blood sugar measured" },
                new Barrier { Id = 129, Category = "bloodsugar", Order = 4, Text = "I have mobility limitations" },
                new Barrier { Id = 131, Category = "bloodsugar", Order = 5, Text = "I am afraid of the results from my blood test" },
                new Barrier { Id = 132, Category = "bloodsugar", Order = 6, Text = "I am afraid of needles" },
                new Barrier { Id = 133, Category = "bloodpressure", Order = 1, Text = "I do not see the point" },
                new Barrier { Id = 134, Category = "bloodpressure", Order = 2, Text = "I do not think it will do me any good" },
                new Barrier { Id = 135, Category = "bloodpressure", Order = 3, Text = "I do not have time" },
                new Barrier { Id = 136, Category = "bloodpressure", Order = 4, Text = "I do not know where I can get my blood pressure measured" },
                new Barrier { Id = 137, Category = "bloodpressure", Order = 5, Text = "It is hard to get an appointment at the GP clinic to get my blood pressure measured" },
                new Barrier { Id = 138, Category = "bloodpressure", Order = 6, Text = "I have mobility limitations" },
                new Barrier { Id = 140, Category = "bloodpressure", Order = 7, Text = "I am afraid of my blood pressure results" }
            );

            modelBuilder.Entity<Intervention>().HasData
            (
                new { Id = 1, Category = "smoking", Text = "Direct me to Southwark's directory of activities and clubs for things to do with my friends that do not involve smoking", Url = "https://www.southwark.gov.uk/leisure-and-sport/local-sport-and-physical-activities", LinkTitle = "Southwark Directory of Physical Activities and Clubs", LinkDescription = "Directory of physical activities and clubs in Southwark ", BarrierId = 1 },
                new { Id = 2, Category = "smoking", Text = "Direct me to my local support services that can provide me with smoking cessation aids (such as nicotine replacement, Champix or e-cigarettes)", Url = "https://www.southwark.gov.uk/health-and-wellbeing/health-advice-and-support/stop-smoking?chapter=3", LinkTitle = "Southwark website - stop smoking telephone support page", LinkDescription = "Stop smoking support services in Southwark", BarrierId = 2 },
                new { Id = 3, Category = "smoking", Text = "Show me strategies online to quit smoking", Url = "https://www.nhs.uk/live-well/quit-smoking/10-self-help-tips-to-stop-smoking/", LinkTitle = "NHS Quitting strategies", LinkDescription = "10 self-help tips to stop smoking on the NHS website", BarrierId = 3 },
                new { Id = 4, Category = "smoking", Text = "Direct me to a pharmacy that can help me quit smoking", Url = "https://www.southwark.gov.uk/health-and-wellbeing/health-advice-and-support/stop-smoking?chapter=4", LinkTitle = "Southwark website - face to face", LinkDescription = "Face-to-face stop smoking support services in Southwark ", BarrierId = 3 },
                new { Id = 5, Category = "smoking", Text = "Direct me to a telephone service that can help me quit smoking", Url = "https://www.southwark.gov.uk/health-and-wellbeing/health-advice-and-support/stop-smoking?chapter=3", LinkTitle = "Southwark website - stop smoking telephone support page", LinkDescription = "Stop smoking telephone support services in Southwark", BarrierId = 3 },
                new { Id = 6, Category = "smoking", Text = "Direct me to the Headspace app for an alternative healthy, relaxing activity to do", Url = "https://www.headspace.com/", LinkTitle = "Headspace", LinkDescription = "Headspace meditation and sleep app ", BarrierId = 6 },
                new { Id = 7, Category = "smoking", Text = "Direct me to a local service that can help me make a plan to quit smoking", Url = "https://southwark.everyonehealth.co.uk/stop-smoking-service/", LinkTitle = "Southwark Stop Smoking Service", LinkDescription = "Southwark Stop Smoking Service for plans to quit smoking", BarrierId = 7 },
                new { Id = 8, Category = "smoking", Text = "Direct me to an app that can help to keep me motivated to quit smoking", Url = "https://www.nhs.uk/better-health/quit-smoking/", LinkTitle = "NHS Smoke Free App", LinkDescription = "NHS Smoke Free App", BarrierId = 8 },
                new { Id = 9, Category = "smoking", Text = "Send me information about the benefits of stopping smoking", Url = "https://www.nhs.uk/live-well/quit-smoking/", LinkTitle = "NHS Benefits of stopping smoking", LinkDescription = "NHS Benefits of stopping smoking", BarrierId = 9 },
                new { Id = 10, Category = "smoking", Text = "Direct me to my local support services that provide me with tools to help me manage my cravings", Url = "https://www.southwark.gov.uk/health-and-wellbeing/health-advice-and-support/stop-smoking?chapter=3", LinkTitle = "Southwark website - stop smoking telephone support page", LinkDescription = "Southwark Stop Smoking support nicotine cravings", BarrierId = 10 },
                new { Id = 11, Category = "smoking", Text = "Direct me to a free telephone consultation for smoking cessation services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Stop Smoking Services", LinkDescription = "Southwark Healthy Lifestyle Hub " },
                new { Id = 12, Category = "smoking", Text = "Direct me to Southwark's digital health and wellbeing coach", Url = "https://southwark.health-coach.app/", LinkTitle = "Southwark's digital health and wellbeing coach", LinkDescription = "Southwark's digital health and wellbeing coach" },
                new { Id = 13, Category = "weight", Text = "Send me information on what is included in a healthy diet", Url = "https://www.nhs.uk/live-well/eat-well/the-eatwell-guide/", LinkTitle = "NHS healthy guudlines", LinkDescription = "NHS Healthy eating guidelines", BarrierId = 11 },
                new { Id = 14, Category = "weight", Text = "Send me to the NHS Weight Loss Plan", Url = "https://www.nhs.uk/better-health/lose-weight/", LinkTitle = "NHS weight loss plan", LinkDescription = "NHS Weight loss plan", BarrierId = 12 },
                new { Id = 15, Category = "weight", Text = "Direct me to my local Slimming World group", Url = "https://www.slimmingworld.co.uk/nearest-group-search", LinkTitle = "Slimming world", LinkDescription = "My local Slimming World group", BarrierId = 13 },
                new { Id = 16, Category = "weight", Text = "Send me tips and recipes on how to eat healthily on a budget", Url = "https://www.nhs.uk/live-well/eat-well/20-tips-to-eat-well-for-less/?tabname=recipes-and-tips", LinkTitle = "NHS Eat Well for Less", LinkDescription = "NHS Recipes and tips to eat well for less", BarrierId = 14 },
                new { Id = 17, Category = "weight", Text = "Direct me to Southwark's food access services", Url = "https://www.southwark.gov.uk/health-and-wellbeing/health-advice-and-support/healthy-eating?chapter=6", LinkTitle = "Southwark Food Access Services", LinkDescription = "Food access services in Southwark", BarrierId = 15 },
                new { Id = 18, Category = "weight", Text = "Direct me to the Headspace app to help me de-stress", Url = "https://www.headspace.com/", LinkTitle = "Headspace", LinkDescription = "Headspace meditation and sleep app ", BarrierId = 16 },
                new { Id = 19, Category = "weight", Text = "Direct me to free swim and gym facilities in Southwark", Url = "https://www.southwark.gov.uk/leisure-and-sport/free-swim-and-gym", LinkTitle = "Free Swim and Gym", LinkDescription = "Access to free swim and gym facilities in Southwark", BarrierId = 17 },
                new { Id = 20, Category = "weight", Text = "Send me information about the benefits of exercise ", Url = "https://www.nhs.uk/live-well/exercise/exercise-health-benefits/", LinkTitle = "NHS Exercise Health Benefits", LinkDescription = "NHS Health benefits of exercise", BarrierId = 18 },
                new { Id = 21, Category = "weight", Text = "Show me how to access vouchers for weight management support groups, to connect with others that might experience similar challenges to me", Url = "https://southwark.everyonehealth.co.uk/services/weight-management/", LinkTitle = "Vouchers for Slimming World and Weight Watchers", LinkDescription = "Vouchers for Slimming World and Weight Watchers", BarrierId = 19 },
                new { Id = 22, Category = "weight", Text = "Direct me to a low impact workout video for beginners on YouTube to show me how to get started to moving more", Url = "https://www.YouTube.com/watch?v=7HqGCwt4F1I", LinkTitle = "ULTIMATE BEGINNERS Low Impact Workout | The Body Coach TV (Joe Wicks)", LinkDescription = "Joe Wicks low impact workout video for beginners", BarrierId = 20 },
                new { Id = 23, Category = "weight", Text = "Direct me to an app that can help me to track my diet", Url = "https://www.myfitnesspal.com/", LinkTitle = "My Fitness Pal App", LinkDescription = "My Fitness Pal App to track my diet ", BarrierId = 21 },
                new { Id = 24, Category = "weight", Text = "Send me a link to holistic healthy weight services for people with a BMI 30+", Url = "https://www.guysandstthomas.nhs.uk/our-services/nutrition-and-dietetics/south-east-London-healthy-weight-programme-new.aspx", LinkTitle = "Southwark healthy weight programme", LinkDescription = "Southwark healthy weight programme" },
                new { Id = 25, Category = "weight", Text = "Send me a link to holistic healthy weight services for people with a BMI 40+", Url = "https://www.guysandstthomas.nhs.uk/our-services/nutrition-and-dietetics/south-east-London-healthy-weight-programme-new.aspx", LinkTitle = "South East London healthy weight programme (balance and fast)", LinkDescription = "Balance and Fast: South East London healthy weight programme" },
                new { Id = 26, Category = "weight", Text = "Direct me to an app to track my activity and help me set goals", Url = "https://www.nhs.uk/oneyou/active10/home/", LinkTitle = "NHS Active10", LinkDescription = "NHS Active10 ", BarrierId = 22 },
                new { Id = 27, Category = "weight", Text = "Direct me to Southwark's digital health and wellbeing coach", Url = "https://southwark.health-coach.app/", LinkTitle = "Southwark Health Coach App", LinkDescription = "Southwark's digital health and wellbeing coach" },
                new { Id = 28, Category = "weight", Text = "Direct me to a free telephone consultation for weight management services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Healthy Lifestyle Hub ", LinkDescription = "Southwark Healthy Lifestyle Hub " },
                new { Id = 29, Category = "weight", Text = "Direct me to inspirational stories about people that do not think they are sporty people (like me)", Url = "https://www.thisgirlcan.co.uk/stories/jen/", LinkTitle = "This Girl Can Our Stories (Jen)", LinkDescription = "Our Stories, from This Girl Can", BarrierId = 23 },
                new { Id = 30, Category = "move", Text = "Direct me to YouTube videos to inspire me to move more", Url = "https://www.YouTube.com/watch?v=SNVwDam-gSY", LinkTitle = "Sports ", LinkDescription = "Return to play - motivational sports video", BarrierId = 24 },
                new { Id = 31, Category = "move", Text = "Direct me to my nearest RunTogether group so that I can go running with other people", Url = "https://runtogether.co.uk/group-running/find-a-runtogether-group-run/", LinkTitle = "RunTogether running group", LinkDescription = "RunTogether running group", BarrierId = 25 },
                new { Id = 32, Category = "move", Text = "Direct me to the We Are Undefeatable website to help me find activities that are right for me with my health condition ", Url = "https://weareundefeatable.co.uk/getting-started", LinkTitle = "We are undefeatable", LinkDescription = "We are undefeatable - getting started", BarrierId = 26 },
                new { Id = 33, Category = "move", Text = "Direct me to free outdoor exercise activities", Url = "https://www.sportengland.org/jointhemovement?section=get_active_away_from_home", LinkTitle = "Sport England", LinkDescription = "Join the movement, Sport England", BarrierId = 27 },
                new { Id = 34, Category = "move", Text = "Direct me to information on healthy exercise levels", Url = "https://www.nhs.uk/live-well/exercise/", LinkTitle = "NHS LiveWell Exercise", LinkDescription = "NHS Exercise levels", BarrierId = 28 },
                new { Id = 35, Category = "move", Text = "Direct me to the Couch to 5K app and online programme", Url = "https://www.nhs.uk/live-well/exercise/get-running-with-couch-to-5k/", LinkTitle = "Couch to 5K App", LinkDescription = "Get running with Couch to 5K", BarrierId = 29 },
                new { Id = 36, Category = "move", Text = "Show me specialised group activity programmes that I can be referred onto by my GP if I am eligible ", Url = "https://southwark.everyonehealth.co.uk/services/gp-exercise-referral/", LinkTitle = "Exercise on Referral", LinkDescription = "Kickstart, Active Boost and Cardiactive - Southwark exercise programmes ", BarrierId = 30 },
                new { Id = 37, Category = "move", Text = "Direct me to my nearest walking group (for all abilities) ", Url = "https://www.walkingforhealth.org.uk/walkfinder/london/fusion-health-walks-southwark", LinkTitle = "Everyone Health Walks Southwark/Walking for Health", LinkDescription = "Everyone Health Walks Southwark", BarrierId = 25 },
                new { Id = 38, Category = "move", Text = "Direct me to a low impact workout video for beginners on YouTube to show me how to get started to moving more", Url = "https://www.YouTube.com/watch?v=7HqGCwt4F1I", LinkTitle = "ULTIMATE BEGINNERS Low Impact Workout | The Body Coach TV (Joe Wicks)", LinkDescription = "Joe Wicks low impact workout video for beginners", BarrierId = 32 },
                new { Id = 39, Category = "move", Text = "Direct me to local sports and physical activities for people like me ", Url = "https://www.southwark.gov.uk/leisure-and-sport/local-sport-and-physical-activities", LinkTitle = "Directory of physical activities and clubs in Southwark ", LinkDescription = "Directory of physical activities and clubs in Southwark ", BarrierId = 33 },
                new { Id = 40, Category = "move", Text = "Send me information about the benefits of exercise ", Url = "https://www.nhs.uk/live-well/exercise/exercise-health-benefits/", LinkTitle = "NHS Exercise Health Benefits", LinkDescription = "NHS Benefits of exercise", BarrierId = 34 },
                new { Id = 41, Category = "move", Text = "Direct me to free swim and gym facilities in Southwark", Url = "https://www.southwark.gov.uk/leisure-and-sport/free-swim-and-gym", LinkTitle = "Free Swim and Gym", LinkDescription = "Access to free swim and gym facilities in Southwark", BarrierId = 35 },
                new { Id = 42, Category = "move", Text = "Direct me to inspirational stories about people that think like me", Url = "https://www.thisgirlcan.co.uk/stories/jen/", LinkTitle = "This Girl Can Our Stories (Jen)", LinkDescription = "Our Stories, from This Girl Can", BarrierId = 36 },
                new { Id = 43, Category = "move", Text = "Send me information on how I can fit more movement into my day", Url = "https://www.nhs.uk/live-well/exercise/get-active-your-way/", LinkTitle = "NHS Get Active Your Way", LinkDescription = "Get active your way - NHS", BarrierId = 37 },
                new { Id = 44, Category = "move", Text = "Direct me to Southwark's digital health and wellbeing coach", Url = "https://southwark.health-coach.app/", LinkTitle = "Southwark Health Coach App", LinkDescription = "Southwark's digital health and wellbeing coach" },
                new { Id = 45, Category = "move", Text = "Direct me to a free telephone consultation for physical activity services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Healthy Lifestyle Hub ", LinkDescription = "Southwark Healthy Lifestyle Hub for services to help manage weight, diet, physical activity, mental wellbeing, alcohol intake and/or smoking habits" },
                new { Id = 46, Category = "alcohol", Text = "Send me an online tool to help me discover my drinking risk level and set a plan to reduce my drinking", Url = "https://www.drinkaware.co.uk/tools/drink-free-days", LinkTitle = "DrinkAware Drink Free Days", LinkDescription = "Drinkaware drink free days", BarrierId = 38 },
                new { Id = 47, Category = "alcohol", Text = "Direct me to information on the health risks of drinking alcohol", Url = "https://www.nhs.uk/conditions/alcohol-misuse/risks/", LinkTitle = "NHS Risks of drinking alcohol", LinkDescription = "NHS Alcohol misuse risks", BarrierId = 39 },
                new { Id = 48, Category = "alcohol", Text = "Send me tips on how to cut down on my alcohol consumption", Url = "https://www.nhs.uk/live-well/alcohol-support/tips-on-cutting-down-alcohol/", LinkTitle = "NHS Tips on cutting down alcohol", LinkDescription = "NHS Tips on cutting down - Alcohol support", BarrierId = 40 },
                new { Id = 49, Category = "alcohol", Text = "Direct me to volunteering opportunities in Southwark to help me meet new people and find ways to socialise without alcohol ", Url = "https://www.communitysouthwark.org/Pages/Category/alt-volunteer-listing-page", LinkTitle = "Community Southwark", LinkDescription = "Volunteering opportunities in Southwark", BarrierId = 41 },
                new { Id = 50, Category = "alcohol", Text = "Direct me to my nearest alcoholics anonymous (AA)  group for support from those that understand what I might be going through", Url = "https://www.alcoholics-anonymous.org.uk/", LinkTitle = "AA Groups", LinkDescription = "Alcoholics Anonymous Support Group", BarrierId = 42 },
                new { Id = 51, Category = "alcohol", Text = "Direct me to an app to help replace my drinking with something healthy (Headspace)", Url = "https://www.headspace.com/", LinkTitle = "Headspace", LinkDescription = "Headspace meditation and sleep app ", BarrierId = 43 },
                new { Id = 52, Category = "alcohol", Text = "Send me tips on how I can change my environment to help me cut down my alcohol consumption at home ", Url = "https://www.drinkaware.co.uk/advice/how-to-reduce-your-drinking/how-to-cut-down-on-alcohol-at-home", LinkTitle = "Drink Aware Cut Down on Alcohol at Home", LinkDescription = "Drink Aware: how to cut down on alcohol at home", BarrierId = 44 },
                new { Id = 53, Category = "alcohol", Text = "Direct me to Southwark Talking Therapies, my local free self-referral NHS talking therapies service, to find support for my mental wellbeing", Url = "https://slam-iapt.nhs.uk/", LinkTitle = "SLAM IAPT", LinkDescription = "Talking Therapies Southwark NHS Trust", BarrierId = 45 },
                new { Id = 54, Category = "alcohol", Text = "Connect me to local services that can give me extra help in changing my drinking behaviours", Url = "https://www.changegrowlive.org/drug-alcohol-service-southwark", LinkTitle = "CGL", LinkDescription = "Drug and alcohol services - Southwark", BarrierId = 46 },
                new { Id = 55, Category = "alcohol", Text = "Direct me to Southwark's digital health and wellbeing coach", Url = "https://southwark.health-coach.app/", LinkTitle = "Southwark Health Coach App", LinkDescription = "Southwark's digital health and wellbeing coach" },
                new { Id = 56, Category = "alcohol", Text = "Direct me to a free telephone consultation for mental wellbeing services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Healthy Lifestyle Hub ", LinkDescription = "Southwark Healthy Lifestyle Hub for services to help manage weight, diet, physical activity, mental wellbeing, alcohol intake and/or smoking habits" },
                new { Id = 57, Category = "mental", Text = "Direct me to Southwark Talking Therapies (a free NHS self-referral therapy service) to find a talking therapy that’s right for me", Url = "https://talkingtherapiessouthwark.nhs.uk/", LinkTitle = "Talking therapies Southwark", LinkDescription = "Talking Therapies Southwark NHS Trust", BarrierId = 47 },
                new { Id = 58, Category = "mental", Text = "Direct me to Southwark's Wellbeing Hub for information and support on mental wellbeing", Url = "Southwark Wellbeing Hub - Southwark Wellbeing Hub (together-uk.org)", LinkTitle = "Southwark Wellbeing Hub Peer Support", LinkDescription = "Southwark Wellbeing Hub", BarrierId = 48 },
                new { Id = 59, Category = "mental", Text = "Show me how physical activity can be beneficial for my mental wellbeing", Url = "https://www.mentalhealth.org.uk/publications/how-to-using-exercise", LinkTitle = "Mental Health Foundation", LinkDescription = "Look after your mental health using exercise", BarrierId = 49 },
                new { Id = 60, Category = "mental", Text = "Direct me to a free telephone consultation for mental wellbeing services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Healthy Lifestyle Hub", LinkDescription = "Southwark Healthy Lifestyle Hub for services to help manage weight, diet, physical activity, mental wellbeing, alcohol intake and/or smoking habits" },
                new { Id = 61, Category = "mental", Text = "Direct me to a range of online helpful mental wellbeing resources that I can use to fit in with my busy lifestyle", Url = "https://www.good-thinking.uk/", LinkTitle = "Good thinking", LinkDescription = "Good Thinking Digital NHS service", BarrierId = 50 },
                new { Id = 62, Category = "mental", Text = "Direct me to a service that provides one-to-one online chat sessions with experienced counsellors", Url = "https://www.qwell.io/", LinkTitle = "Qwell", LinkDescription = "Qwell: online emotional wellbeing and mental health support services for adults", BarrierId = 50 },
                new { Id = 63, Category = "mental", Text = "Direct me to Southwark Talking Therapies, my local free self-referral NHS talking therapies service, to find online support for my mental wellbeing that can fit around my busy lifestyle", Url = "https://talkingtherapiessouthwark.nhs.uk/", LinkTitle = "Talking therapies Southwark", LinkDescription = "Talking Therapies Southwark NHS Trust", BarrierId = 50 },
                new { Id = 64, Category = "mental", Text = "Direct me to my nearest walking group (for all abilities)", Url = "https://www.walkingforhealth.org.uk/walkfinder/london/fusion-health-walks-southwark", LinkTitle = "Everyone Health Walks Southwark/Walking for Health", LinkDescription = "Everyone Health Walks Southwark", BarrierId = 53 },
                new { Id = 65, Category = "mental", Text = "Direct me to local sports and physical activities for me to explore and try", Url = "https://www.southwark.gov.uk/leisure-and-sport/local-sport-and-physical-activities", LinkTitle = "Directory of physical activities and clubs in Southwark", LinkDescription = "Directory of physical activities and clubs in Southwark", BarrierId = 53 },
                new { Id = 66, Category = "mental", Text = "Direct me to apps for getting better sleep", Url = "https://www.good-thinking.uk/sleep/", LinkTitle = "Good Thinking Sleep Aid Apps", LinkDescription = "Good Thinking Digital NHS service - Apps for getting better sleep", BarrierId = 55 },
                new { Id = 67, Category = "mental", Text = "Direct me to free NHS therapy resources to help me sleep", Url = "https://talkingtherapiessouthwark.nhs.uk/self-help-resources/therapy-resources/", LinkTitle = "Talking therapies Southwark", LinkDescription = "Therapy Resources, Sleep - Talking Therapies Southwark NHS Trust", BarrierId = 55 },
                new { Id = 68, Category = "mental", Text = "Direct me to the Headspace app to help me relax", Url = "https://www.headspace.com/", LinkTitle = "Headspace", LinkDescription = "Headspace meditation and sleep app", BarrierId = 57 },
                new { Id = 69, Category = "mental", Text = "Direct me to the Good Thinking Digital Mental Wellbeing website for resources on how to deal with stress", Url = "https://www.good-thinking.uk/stress/", LinkTitle = "Good thinking", LinkDescription = "Good Thinking Digital NHS service - Deal with stress", BarrierId = 57 },
                new { Id = 70, Category = "mental", Text = "Direct me to Talking Therapies Southwark, my local free NHS talking therapies service, for emotional and mental health support from those that have an understanding of what I am going through", Url = "https://talkingtherapiessouthwark.nhs.uk/", LinkTitle = "Talking therapies Southwark", LinkDescription = "Talking Therapies Southwark NHS Trust", BarrierId = 59 },
                new { Id = 71, Category = "mental", Text = "Direct me to online safe and anonymous peer support communities so that I can connect with others that have a better understanding of what I might be going through", Url = "https://www.qwell.io/", LinkTitle = "Qwell App", LinkDescription = "Qwell: online emotional wellbeing and mental health support services for adults", BarrierId = 59 },
                new { Id = 72, Category = "mental", Text = "Direct me to peer support services in Southwark so that I can talk to someone who has been through something similar to me", Url = "https://www.together-uk.org/southwark-wellbeing-hub/get-support/peer-support-self-management-groups/", LinkTitle = "Together Southwark Peer Support", LinkDescription = "Southwark wellbeing Hub Peer Support", BarrierId = 59 },
                new { Id = 73, Category = "mental", Text = "Connect me to Southwark London Cares for opportunities to volunteer and socialise", Url = "https://southlondoncares.org.uk/social-clubs", LinkTitle = "Southwark London Cares", LinkDescription = "Social clubs in London", BarrierId = 62 },
                new { Id = 74, Category = "mental", Text = "Direct me to Time & Talents in Southwark for opportunities to volunteer and socialise", Url = "https://www.timeandtalents.org.uk/", LinkTitle = "", LinkDescription = "Time & Talents Southwark community organisation for opportunities to volunteer and socialise", BarrierId = 62 },
                new { Id = 75, Category = "mental", Text = "Direct me to Link Age in Southwark for befriending, group activities and opportunities to socialise for older adults (aged 60 years plus or adults living with dementia)", Url = "https://www.linkagesouthwark.org/", LinkTitle = "", LinkDescription = "Link Age Southwark for befriending, group activities and opportunities to socialise for older adults (aged 60 years plus or adults living with dementia)", BarrierId = 62 },
                new { Id = 76, Category = "mental", Text = "Direct me to free workshops and events for mental wellbeing such as creative writing, arts appreciation and mindfulness", Url = "https://www.ticketsource.co.uk/southwark-wellbeing-hub", LinkTitle = "Together Southwark Wellbeing Workshops", LinkDescription = "Free workshops and events for mental wellbeing such as creative writing, arts appreciation and mindfulness", BarrierId = 65 },
                new { Id = 77, Category = "mental", Text = "Direct me to an informal, creative and safe space to take part in a range of creative activities and meet people", Url = "https://www.dragoncafe.co.uk/", LinkTitle = "The Dragon Cafe Charity ", LinkDescription = "The Dragon Cafe: an informal, creative and safe space for people to meet and take part in a range of activities", BarrierId = 65 },
                new { Id = 78, Category = "mental", Text = "Direct me to NHS therapy self-help videos to help me set goals and learn strategies that I can use to improve my mental wellbeing", Url = "https://talkingtherapiessouthwark.nhs.uk/self-help-resources/therapy-resources/diy-cbt-cognitive-behavioural-therapy-videos/", LinkTitle = "NHS DIY Talking Therapies", LinkDescription = "DIY CBT- Talking therapies Southwark NHS Trust", BarrierId = 67 },
                new { Id = 79, Category = "mental", Text = "Direct me to Southwark's digital health and wellbeing coach", Url = "https://southwark.health-coach.app/", LinkTitle = "Southwark Health Coach App", LinkDescription = "Southwark's digital health and wellbeing coach" },
                new { Id = 80, Category = "mental", Text = "Direct me to help, support and local services for LGBTQ+ people", Url = "https://www.stonewall.org.uk/help-and-advice", LinkTitle = "Stonewall Charity", LinkDescription = "Stonewall help and advice", BarrierId = 68 },
                new { Id = 81, Category = "mental", Text = "Direct me to a range of LGBTQ+ organisations in Southwark that can offer help to people experiencing issues relating to sexuality, gender and identity", Url = "https://www.communitysouthwark.org/news/support-for-lgbtq-people", LinkTitle = "Community Southwark Support for LGBTQ+ community", LinkDescription = "Community Southwark: LGBTQ+ organisations in Southwark that can offer help to people experiencing issues relating to sexuality, gender and identity", BarrierId = 68 },
                new { Id = 82, Category = "mental", Text = "Direct me to specialist online groups and workshops covering a range of topics related to psychological wellbeing, such as coping well during the pandemic, bereavement, mindfulness, LGBTQ wellbeing, student wellbeing, and ethnic minority empowerment.", Url = "https://talkingtherapiessouthwark.nhs.uk/about-us/treatment-options/", LinkTitle = "", LinkDescription = "Talking Therapies Southwark NHS Trust - specialist online groups and workshops covering a range of topics related to psychological wellbeing, such as coping well during the pandemic, bereavement, mindfulness, LGBTQ wellbeing, student wellbeing, and ethnic minority empowerment.", BarrierId = 70 },
                new { Id = 83, Category = "mental", Text = "Direct me to Southwark's Citizen Advice centre for housing advice", Url = "https://www.citizensadvicesouthwark.org.uk/projects-and-services/outreach-projects/", LinkTitle = "Southwark Citizen Advice", LinkDescription = "Southwark's Citizen Advice centre for housing advice", BarrierId = 71 },
                new { Id = 84, Category = "mental", Text = "Direct me to online links that can provide me with information, advice and legal help on a variety of housing issues", Url = "https://www.southwark.gov.uk/benefits-and-support/advice-services?chapter=5", LinkTitle = "Southwark Website of services for housing support", LinkDescription = "Southwark Council: information, advice and legal help on a variety of housing issues", BarrierId = 71 },
                new { Id = 88, Category = "mental", Text = "Direct me to Southwark Carers for support services to help me take care of my own wellbeing", Url = "https://www.southwarkcarers.org.uk/", LinkTitle = "Southwark Carers", LinkDescription = "Southwark Carers support services for carer's wellbeing", BarrierId = 76 },
                new { Id = 89, Category = "mental", Text = "Direct me to Southwark Council's emergency and hardship scheme applications for support with my household bills", Url = "https://www.southwark.gov.uk/benefits-and-support/hardship-fund", LinkTitle = "Southwark hardship fund (bills)", LinkDescription = "Southwark Council's emergency and hardship scheme applications for support with household bills", BarrierId = 77 },
                new { Id = 85, Category = "mental", Text = "Direct me to organisations in Southwark that can help access employment information or legal advice about work-related issues", Url = "https://www.southwark.gov.uk/benefits-and-support/advice-services?chapter=4", LinkTitle = "Southwark employment support", LinkDescription = "Southwark Council: organisations in Southwark that can help access employment information or legal advice about work-related issues", BarrierId = 73 },
                new { Id = 86, Category = "mental", Text = "Direct me to the Children and Family centres in Southwark that provide advice and support for expectant mothers and parents/carers up until their children go into reception class at primary school", Url = "https://www.southwark.gov.uk/childcare-and-parenting/advice-and-support-for-families/children-s-centres", LinkTitle = "Southwark Family Centres", LinkDescription = "Children and Family centres in Southwark that provide advice and support for parents and carers (services are for expectant mothers and parents up until their children go into reception class at primary school)", BarrierId = 74 },
                new { Id = 87, Category = "mental", Text = "Direct me to the Southwark Family Information Service (FIS) for information on local services available to children, young people and families in Southwark", Url = "https://www.southwark.gov.uk/childcare-and-parenting/advice-and-support-for-families/family-information-service", LinkTitle = "FIS", LinkDescription = "Southwark Family Information Service (FIS) for information on local services available to children, young people and families in Southwark", BarrierId = 74 },
                new { Id = 90, Category = "mental", Text = "Direct me to the Southwark Foodbank for emergency food and additional support alongside the underlying issues behind my food crisis", Url = "https://southwark.foodbank.org.uk/get-help/", LinkTitle = "Southwark Foodbank", LinkDescription = "Southwark Foodbank for emergency food and additional support alongside the underlying issues behind the crisis", BarrierId = 78 },
                new { Id = 91, Category = "mental", Text = "Direct me to Southwark's Citizen Advice centre for debt and money advice", Url = "https://www.citizensadvicesouthwark.org.uk/projects-and-services/outreach-projects/", LinkTitle = "Citizen Advice Southwark", LinkDescription = "Southwark's Citizen Advice centre for debt and money advice", BarrierId = 79 },
                new { Id = 92, Category = "mental", Text = "Direct me to a range of services that provide information, advice and legal help in relation to money", Url = "https://www.southwark.gov.uk/benefits-and-support/advice-services?chapter=3", LinkTitle = "Southwark advice", LinkDescription = "Southwark Council: services that provide information, advice and legal help in relation to money", BarrierId = 79 },
                new { Id = 93, Category = "mental", Text = "Direct me to specialist online groups and workshops for bereavement through Southwark's NHS Talking Therapies", Url = "https://talkingtherapiessouthwark.nhs.uk/about-us/treatment-options/", LinkTitle = "Talking therapies Southwark", LinkDescription = "Talking Therapies Southwark NHS Trust - specialist online groups and workshops covering a range of topics related to psychological wellbeing, including bereavement", BarrierId = 81 },
                new { Id = 94, Category = "mental", Text = "Direct me to a national organisation that provide bereavement helplines and assistance finding services", Url = "https://www.cruse.org.uk/get-support/", LinkTitle = "Cruse Charity", LinkDescription = "Cruse Charity: bereavement helplines and assistance finding services", BarrierId = 81 },
                new { Id = 95, Category = "gp", Text = "Show me real stories of people with heart disease to motivate me to go to the GP clinic", Url = "https://www.bhf.org.uk/informationsupport/heart-matters-magazine/my-story", LinkTitle = "BHF My Story", LinkDescription = "Real stories - heart disease", BarrierId = 83 },
                new { Id = 96, Category = "gp", Text = "Show me simple things that I can do to look after my heart health", Url = "https://www.nhs.uk/live-well/healthy-body/", LinkTitle = "NHS Healthy Body", LinkDescription = "NHS Healthy Body", BarrierId = 84 },
                new { Id = 97, Category = "gp", Text = "Send me information on how to book a weekend or evening consultation with a GP", Url = "https://www.nhs.uk/nhs-services/gps/gp-appointments-and-bookings/", LinkTitle = "", LinkDescription = "GP Appointments and booking", BarrierId = 85 },
                new { Id = 98, Category = "gp", Text = "Send me information on how I can book a GP appointment online", Url = "https://www.nhs.uk/nhs-services/gps/gp-appointments-and-bookings/", LinkTitle = "", LinkDescription = "GP Appointments and booking", BarrierId = 86 },
                new { Id = 99, Category = "gp", Text = "Send me information on how to have a telephone or online consultation with a GP", Url = "https://www.nhs.uk/nhs-services/gps/gp-appointments-and-bookings/", LinkTitle = "", LinkDescription = "GP Appointments and booking", BarrierId = 87 },
                new { Id = 100, Category = "gp", Text = "Show me all the different ways I can access health advice ", Url = "https://www.nhs.uk/", LinkTitle = "", LinkDescription = "NHS Health Advice", BarrierId = 88 },
                new { Id = 101, Category = "gp", Text = "Send me advice on how I can prepare for an appointment with a GP and tips on how to lower my anxiety over fear for the appointment", Url = "https://www.nhs.uk/nhs-services/gps/what-to-ask-your-doctor/", LinkTitle = "", LinkDescription = "NHS What to ask your doctor", BarrierId = 89 },
                new { Id = 102, Category = "gp", Text = "Send me advice on how to make the most out of my appointment ", Url = "https://www.healthwatch.co.uk/advice-and-information/2021-07-26/top-tips-get-most-out-your-gp-appointment", LinkTitle = "", LinkDescription = "Tips to get the most out of your GP appointment", BarrierId = 90 },
                new { Id = 103, Category = "improvecholesterol", Text = "Send me information on easy ways to eating healthily to help lower my cholesterol", Url = "https://www.heartuk.org.uk/healthy-living/introduction", LinkTitle = "", LinkDescription = "Healthy living for your heart", BarrierId = 91 },
                new { Id = 104, Category = "improvecholesterol", Text = "Send me ideas on how I can fit more movement into my day", Url = "https://www.nhs.uk/live-well/exercise/get-active-your-way/", LinkTitle = "NHS Get Active Your Way", LinkDescription = "Get active your way - NHS", BarrierId = 92 },
                new { Id = 105, Category = "improvecholesterol", Text = "Direct me to a low impact workout video for beginners on YouTube to show me how to get started to moving more", Url = "https://www.YouTube.com/watch?v=7HqGCwt4F1I", LinkTitle = "ULTIMATE BEGINNERS Low Impact Workout | The Body Coach TV (Joe Wicks)", LinkDescription = "Joe Wicks low impact workout video for beginners", BarrierId = 93 },
                new { Id = 106, Category = "improvecholesterol", Text = "Direct me to the Headspace app to help me de-stress", Url = "https://www.headspace.com/", LinkTitle = "Headspace", LinkDescription = "Headspace meditation and sleep app ", BarrierId = 94 },
                new { Id = 107, Category = "improvecholesterol", Text = "Direct me to information on health risks of high cholesterol", Url = "https://www.heartuk.org.uk/cholesterol/what-is-high-cholesterol", LinkTitle = "", LinkDescription = "What is high cholesterol?", BarrierId = 95 },
                new { Id = 108, Category = "improvecholesterol", Text = "Direct me to commonly asked questions on ways to improve cholesterol levels through healthy lifestyle changes", Url = "https://www.bhf.org.uk/informationsupport/risk-factors/high-cholesterol/five-top-questions-about-lowering-cholesterol", LinkTitle = "", LinkDescription = "How do I lower my cholesterol? Top 5 questions", BarrierId = 96 },
                new { Id = 109, Category = "improvecholesterol", Text = "Find me social activities that do not involve drinking ", Url = "https://www.meetup.com/topics/nondrinker/gb/17/london/", LinkTitle = "MeetUp London Alcohol Free", LinkDescription = "MeetUp Alcohol-free social groups in London", BarrierId = 97 },
                new { Id = 110, Category = "improvecholesterol", Text = "Direct me to volunteering opportunities in Southwark to help me meet new people and find ways to socialise without alcohol ", Url = "https://www.communitysouthwark.org/Pages/Category/alt-volunteer-listing-page", LinkTitle = "Community Southwark", LinkDescription = "Volunteering opportunities in Southwark", BarrierId = 97 },
                new { Id = 111, Category = "improvecholesterol", Text = "Direct me to an app that can help to keep me motivated to quit smoking", Url = "https://www.nhs.uk/better-health/quit-smoking/", LinkTitle = "NHS Smoke Free App", LinkDescription = "NHS Quit Smoking App", BarrierId = 99 },
                new { Id = 112, Category = "improvecholesterol", Text = "Direct me to a free telephone consultation for physical activity, weight management and/or smoking cessation services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Healthy Lifestyle Hub ", LinkDescription = "Southwark Healthy Lifestyle Hub for services to help manage weight, diet, physical activity, mental wellbeing, alcohol intake and/or smoking habits" },
                new { Id = 113, Category = "improvebloodpressure", Text = "Send me top tips on lifestyle changes that I can make to lower my blood pressure", Url = "https://www.bhf.org.uk/informationsupport/heart-matters-magazine/research/blood-pressure/blood-pressure-tips", LinkTitle = "", LinkDescription = "How to reduce blood pressure", BarrierId = 100 },
                new { Id = 114, Category = "improvebloodpressure", Text = "Send me information about the benefits of exercise ", Url = "https://www.nhs.uk/live-well/exercise/exercise-health-benefits/", LinkTitle = "NHS Exercise Health Benefits", LinkDescription = "NHS Benefits of exercise", BarrierId = 101 },
                new { Id = 115, Category = "improvebloodpressure", Text = "Send me real stories of people that have suffered with high blood pressure to motivate me to improve my health", Url = "http://www.bloodpressureuk.org/resources/real-stories/", LinkTitle = "", LinkDescription = "Real Stories - blood pressure", BarrierId = 102 },
                new { Id = 116, Category = "improvebloodpressure", Text = "Direct me to an app that can help to keep me motivated to quit smoking", Url = "https://www.nhs.uk/better-health/quit-smoking/", LinkTitle = "NHS Smoke Free App", LinkDescription = "NHS Quit Smoking App", BarrierId = 103 },
                new { Id = 117, Category = "improvebloodpressure", Text = "Direct me to a range of apps and advice that can help me to get better sleep", Url = "https://www.good-thinking.uk/sleep/", LinkTitle = "Good Thinking Sleep Aid Apps", LinkDescription = "Good Thinking - Apps for getting better sleep", BarrierId = 104 },
                new { Id = 118, Category = "improvebloodpressure", Text = "Send me tips on how to cut down my salt intake to help lower my blood pressure", Url = "https://www.bhf.org.uk/informationsupport/heart-matters-magazine/nutrition/sugar-salt-and-fat/hold-the-salt/seven-salt-slashing-tactics", LinkTitle = "", LinkDescription = "7 salt-slashing techniques", BarrierId = 105 },
                new { Id = 119, Category = "improvebloodpressure", Text = "Send me information on how I can fit more movement into my day", Url = "https://www.nhs.uk/live-well/exercise/get-active-your-way/", LinkTitle = "NHS Get Active Your Way", LinkDescription = "Get active your way - NHS", BarrierId = 106 },
                new { Id = 120, Category = "improvebloodpressure", Text = "Direct me to an app to help track my diet", Url = "https://www.myfitnesspal.com/", LinkTitle = "My Fitness Pal App", LinkDescription = "My Fitness Pal App to track my diet ", BarrierId = 107 },
                new { Id = 121, Category = "improvebloodpressure", Text = "Direct me to the online NHS Weight Loss plan so that I can plan my meals and make healthier food choices to help lower my blood pressure", Url = "https://www.nhs.uk/better-health/lose-weight/", LinkTitle = "NHS weight loss plan", LinkDescription = "NHS Weight loss plan", BarrierId = 108 },
                new { Id = 122, Category = "improvebloodpressure", Text = "Direct me to my local Slimming World group so that I can find others to eat more healthily and be more active with", Url = "https://www.slimmingworld.co.uk/nearest-group-search", LinkTitle = "Slimming world", LinkDescription = "My local Slimming World group", BarrierId = 109 },
                new { Id = 123, Category = "improvebloodpressure", Text = "Direct me to Southwark's digital health and wellbeing coach", Url = "https://southwark.health-coach.app/", LinkTitle = "Southwark Health Coach App", LinkDescription = "Southwark's digital health and wellbeing coach" },
                new { Id = 124, Category = "improvebloodpressure", Text = "Direct me to a free telephone consultation for physical activity, weight management and/or smoking cessation services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Healthy Lifestyle Hub ", LinkDescription = "Southwark Healthy Lifestyle Hub for services to help manage weight, diet, physical activity, mental wellbeing, alcohol intake and/or smoking habits" },
                new { Id = 125, Category = "improvebloodsugar", Text = "Direct me to the NHS Diabetes Prevention Programme self-referral registration page", Url = "https://preventing-diabetes.co.uk/self-referral/", LinkTitle = "", LinkDescription = "NHS Diabetes Prevention Programme" },
                new { Id = 126, Category = "improvebloodsugar", Text = "Direct me to the NHS Weight Loss Plan app so that I can plan my meals and make healthier food choices", Url = "https://www.nhs.uk/better-health/lose-weight/", LinkTitle = "", LinkDescription = "NHS Weight loss plan app", BarrierId = 110 },
                new { Id = 127, Category = "improvebloodsugar", Text = "Send me information about the health consequences of diabetes", Url = "https://www.diabetes.org.uk/guide-to-diabetes/complications", LinkTitle = "", LinkDescription = "Complications of diabetes", BarrierId = 111 },
                new { Id = 128, Category = "improvebloodsugar", Text = "Direct me to Southwark Talking Therapies, my local free self-referral NHS talking therapies service, for support with my mental wellbeing", Url = "https://talkingtherapiessouthwark.nhs.uk/", LinkTitle = "", LinkDescription = "Talking therapies Southwark", BarrierId = 112 },
                new { Id = 129, Category = "improvebloodsugar", Text = "Direct me to an app to help track my diet", Url = "https://www.myfitnesspal.com/", LinkTitle = "", LinkDescription = "My Fitness Pal App to track my diet ", BarrierId = 113 },
                new { Id = 130, Category = "improvebloodsugar", Text = "Direct me to an app that can help me set an exercise plan suitable for me", Url = "https://exi.life/", LinkTitle = "", LinkDescription = "EXi app - 12-week exercise plan", BarrierId = 114 },
                new { Id = 131, Category = "improvebloodsugar", Text = "Direct me to the Couch to 5K app and online programme to help me gradually increase my stamina and to move more", Url = "https://www.nhs.uk/live-well/exercise/get-running-with-couch-to-5k/", LinkTitle = "Couch to 5K App", LinkDescription = "", BarrierId = 115 },
                new { Id = 132, Category = "improvebloodsugar", Text = "Direct me to free swim and gym facilities in Southwark", Url = "https://www.southwark.gov.uk/leisure-and-sport/free-swim-and-gym", LinkTitle = "Free Swim and Gym", LinkDescription = "Access to free swim and gym facilities in Southwark", BarrierId = 116 },
                new { Id = 133, Category = "improvebloodsugar", Text = "Direct me to an app that can tell me amount of sugar in food at when I am food shopping", Url = "https://play.google.com/store/apps/details?id=com.phe.c4lfoodsmart&hl=en_GB&gl=US", LinkTitle = "", LinkDescription = "Change4Life food scanner app", BarrierId = 117 },
                new { Id = 134, Category = "improvebloodsugar", Text = "Direct me to my local Slimming World group so that I can find others to eat more healthily and be more active with", Url = "https://www.slimmingworld.co.uk/nearest-group-search", LinkTitle = "", LinkDescription = "My local Slimming World group", BarrierId = 118 },
                new { Id = 135, Category = "improvebloodsugar", Text = "Direct me to Southwark's digital health and wellbeing coach", Url = "https://southwark.health-coach.app/", LinkTitle = "Southwark Health Coach App", LinkDescription = "Southwark Health Coach App" },
                new { Id = 136, Category = "improvebloodsugar", Text = "Direct me to a free telephone consultation for physical activity, weight management and/or smoking cessation services through Southwark's Healthy Lifestyle Hub", Url = "https://southwark.everyonehealth.co.uk/", LinkTitle = "Southwark Healthy Lifestyle Hub ", LinkDescription = "Southwark Healthy Lifestyle Hub for services to help manage weight, diet, physical activity, mental wellbeing, alcohol intake and/or smoking habits" },
                new { Id = 137, Category = "cholesterol", Text = "Direct me to information on health risks of high cholesterol", Url = "https://www.heartuk.org.uk/cholesterol/what-is-high-cholesterol", LinkTitle = "", LinkDescription = "What is high cholesterol? ", BarrierId = 119 },
                new { Id = 138, Category = "cholesterol", Text = "Help me to book an appointment that fits around my lifestyle", Url = "https://outlook.office365.com/owa/calendar/DigitalHealthCheckSouthwark@everyonehealth.co.uk/bookings/", LinkTitle = "", LinkDescription = "Book a health check test at my leisure centre", BarrierId = 120 },
                new { Id = 139, Category = "cholesterol", Text = "Direct me to the online booking webpage where I can make an appointment to have my cholesterol levels measured at one of Southwark's leisure centres", Url = "https://outlook.office365.com/owa/calendar/DigitalHealthCheckSouthwark@everyonehealth.co.uk/bookings/", LinkTitle = "", LinkDescription = "Book a health check test at my leisure centre", BarrierId = 121 },
                new { Id = 140, Category = "cholesterol", Text = "Direct me to AgeUK for potential transport assistance to get to my health appointment", Url = "https://www.ageuk.org.uk/services/in-your-area/transport/", LinkTitle = "", LinkDescription = "AgeUK Transport services for the elderly and disabled ", BarrierId = 122 },
                new { Id = 141, Category = "cholesterol", Text = "Direct me to tips for driving and using public transport for those with mobility issues", Url = "https://www.nhs.uk/conditions/social-care-and-support-guide/care-services-equipment-and-care-homes/driving-and-using-public-transport/", LinkTitle = "", LinkDescription = "NHS Guidance for driving and using public transport with a mobility issue", BarrierId = 122 },
                new { Id = 142, Category = "cholesterol", Text = "Send me tips on practicing mindfulness for beginners to help lower my anxiety on getting my results", Url = "https://www.therapyforyou.co.uk/post/practicing-mindfulness-for-beginners", LinkTitle = "", LinkDescription = "21 Top Tips on Practicing Mindfulness for Beginners", BarrierId = 124 },
                new { Id = 143, Category = "cholesterol", Text = "Send me tips on overcoming a fear of needles", Url = "https://www.guysandstthomas.nhs.uk/resources/patient-information/all-patients/overcoming-your-fear-of-needles.pdf", LinkTitle = "", LinkDescription = "NHS Overcoming your fear of needles", BarrierId = 125 },
                new { Id = 144, Category = "bloodsugar", Text = "Send me information about the health consequences of diabetes", Url = "https://www.diabetes.org.uk/guide-to-diabetes/complications", LinkTitle = "", LinkDescription = "Complications of diabetes", BarrierId = 126 },
                new { Id = 145, Category = "bloodsugar", Text = "Help me to book an appointment that fits around my lifestyle", Url = "https://outlook.office365.com/owa/calendar/DigitalHealthCheckSouthwark@everyonehealth.co.uk/bookings/", LinkTitle = "", LinkDescription = "Book a health check test at my leisure centre", BarrierId = 127 },
                new { Id = 146, Category = "bloodsugar", Text = "Direct me to the online booking webpage where I can make an appointment to have my blood sugar level measured at one of Southwark's leisure centres", Url = "https://outlook.office365.com/owa/calendar/DigitalHealthCheckSouthwark@everyonehealth.co.uk/bookings/", LinkTitle = "", LinkDescription = "Book a health check test at my leisure centre", BarrierId = 128 },
                new { Id = 147, Category = "bloodsugar", Text = "Direct me to AgeUK for potential transport assistance to get to my health appointment", Url = "https://www.ageuk.org.uk/services/in-your-area/transport/", LinkTitle = "", LinkDescription = "AgeUK Transport services for the elderly and disabled ", BarrierId = 129 },
                new { Id = 148, Category = "bloodsugar", Text = "Direct me to tips for driving and using public transport for those with mobility issues", Url = "https://www.nhs.uk/conditions/social-care-and-support-guide/care-services-equipment-and-care-homes/driving-and-using-public-transport/", LinkTitle = "", LinkDescription = "NHS Guidance for driving and using public transport with a mobility issue", BarrierId = 129 },
                new { Id = 149, Category = "bloodsugar", Text = "Send me tips on practicing mindfulness for beginners to help lower my anxiety on getting my results", Url = "https://www.therapyforyou.co.uk/post/practicing-mindfulness-for-beginners", LinkTitle = "", LinkDescription = "21 Top Tips on Practicing Mindfulness for Beginners", BarrierId = 131 },
                new { Id = 150, Category = "bloodsugar", Text = "Send me tips on overcoming a fear of needles", Url = "https://www.guysandstthomas.nhs.uk/resources/patient-information/all-patients/overcoming-your-fear-of-needles.pdf", LinkTitle = "", LinkDescription = "NHS Overcoming your fear of needles", BarrierId = 132 },
                new { Id = 151, Category = "bloodpressure", Text = "Send me stories of real people with high blood pressure issues", Url = "http://www.bloodpressureuk.org/resources/real-stories/", LinkTitle = "", LinkDescription = "Real stories - high blood pressure", BarrierId = 133 },
                new { Id = 152, Category = "bloodpressure", Text = "Show me the benefits of getting my blood pressure checked", Url = "https://www.bhf.org.uk/informationsupport/heart-matters-magazine/medical/tests/blood-pressure", LinkTitle = "", LinkDescription = "Why should I know my blood pressure? ", BarrierId = 134 },
                new { Id = 153, Category = "bloodpressure", Text = "Give me tips on how to measure my blood pressure at home ", Url = "http://www.bloodpressureuk.org/your-blood-pressure/how-to-lower-your-blood-pressure/monitoring-your-blood-pressure-at-home/how-to-measure-your-blood-pressure-at-home/", LinkTitle = "", LinkDescription = "How to measure your blood pressure at home", BarrierId = 135 },
                new { Id = 154, Category = "bloodpressure", Text = "Show me the different options available to get my blood pressure measured", Url = "http://www.bloodpressureuk.org/your-blood-pressure/getting-diagnosed/where-can-you-get-a-blood-pressure-check/", LinkTitle = "", LinkDescription = "Where to get your blood pressure checked - guidance", BarrierId = 136 },
                new { Id = 155, Category = "bloodpressure", Text = "Direct me to the online booking webpage where I can make an appointment to have my blood pressure measured at one of Southwark's leisure centres", Url = "https://outlook.office365.com/owa/calendar/DigitalHealthCheckSouthwark@everyonehealth.co.uk/bookings/", LinkTitle = "", LinkDescription = "Book a health check test at my leisure centre", BarrierId = 137 },
                new { Id = 156, Category = "bloodpressure", Text = "Direct me to AgeUK for potential transport assistance to get to my health appointment", Url = "https://www.ageuk.org.uk/services/in-your-area/transport/", LinkTitle = "", LinkDescription = "AgeUK Transport services for the elderly and disabled ", BarrierId = 138 },
                new { Id = 157, Category = "bloodpressure", Text = "Direct me to tips for driving and using public transport for those with mobility issues", Url = "https://www.nhs.uk/conditions/social-care-and-support-guide/care-services-equipment-and-care-homes/driving-and-using-public-transport/", LinkTitle = "", LinkDescription = "NHS Guidance for driving and using public transport with a mobility issue", BarrierId = 138 },
                new { Id = 158, Category = "bloodpressure", Text = "Send me tips on practicing mindfulness for beginners to help lower my anxiety on getting my results", Url = "https://www.therapyforyou.co.uk/post/practicing-mindfulness-for-beginners", LinkTitle = "", LinkDescription = "21 Top Tips on Practicing Mindfulness for Beginners", BarrierId = 140 }
            );
        }
    }
}